server:
  error:
    include-stacktrace: on-param # Só exibirar erros previamente passados
    

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?useSSL=false
    username: root
    password: 28112006
  jpa:
    hibernate:
      ddl-auto: update
